# Generated by Django 3.2.8 on 2021-11-19 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
                ('airport', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('flight_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('seat_class', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('path_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('departure', models.CharField(max_length=5)),
                ('destination', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flight_booking.flightclass')),
                ('airline', models.CharField(max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('path_id', models.ForeignKey(db_column='path_id', on_delete=django.db.models.deletion.CASCADE, to='flight_booking.travel')),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetail',
            fields=[
                ('flight_id', models.ForeignKey(db_column='flight_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flight_booking.flight')),
                ('departure_date', models.DateField()),
                ('gate_no', models.CharField(max_length=5)),
            ],
        ),
    ]
